version: '3.8'  
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: CursoSQL2022!
      MSSQL_PID: Developer
      MSSQL_AGENT_ENABLED: 'true'
    ports:
      - "1433:1433" # el primer puerto es el que se expone en el host y el segundo es el puerto del contenedor
    volumes:
      - ./mssql:/var/opt/mssql/data
volumes:
  mssql: